version: '3.8'

services:
  db:
    image: postgres:13
    container_name: sentiment_db
    environment:
      POSTGRES_DB: sentiment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - sentiment_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sentiment_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: sentiment_backend
    environment:
      - DB_HOST=db
      - DB_NAME=sentiment_db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - TWITTER_API_KEY=${TWITTER_API_KEY}
      - TWITTER_API_SECRET=${TWITTER_API_SECRET}
      - TWITTER_ACCESS_TOKEN=${TWITTER_ACCESS_TOKEN}
      - TWITTER_ACCESS_TOKEN_SECRET=${TWITTER_ACCESS_TOKEN_SECRET}
      - TWITTER_BEARER_TOKEN=${TWITTER_BEARER_TOKEN}
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - sentiment_network
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: sentiment_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - sentiment_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  sentiment_network:
    driver: bridge